(defun delete-elems (elem arr)
	(if (not(eq arr nil))
		(if (eq (car arr) elem)
			(delete-elems elem (cdr arr))
			(cons (car arr) (delete-elems elem (cdr arr)))
		)
	)
)

(defun remove-elems (list1 list2)
	(if (not (eq list1 nil))	
		(remove-elems (cdr list1) (delete-elems (car list1) list2))
		list2
	)
)